name: 部署到Cloudflare Pages

on:
  push:
    branches:
      - master  # 根据您的主分支名称调整此处

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: 发布到Cloudflare Pages
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装依赖
        run: |
          if [ -f "package.json" ]; then
            npm install
          fi

      - name: 构建项目
        run: |
          if [ -f "package.json" ] && grep -q "build" package.json; then
            npm run build
          fi

      - name: 部署到Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: live2d-widget  # 修改为您在Cloudflare Pages中的项目名称
          directory: dist  # 指向您的构建输出目录
          # 如果您有自定义域名，可以取消下面这一行的注释
